# Generated by Django 4.1.5 on 2023-01-28 22:05

import annonce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_alter_annonce_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=annonce.models.upload_to),
        ),
    ]
