# Generated by Django 4.0.4 on 2022-12-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='adr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annonce.adress', verbose_name='Adress'),
        ),
    ]
