# Generated by Django 4.1.5 on 2023-01-29 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonce', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fav',
            name='annonce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Annonce', to='annonce.annonce'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fav',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together={('user', 'annonce')},
        ),
        migrations.RemoveField(
            model_name='fav',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='liker',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
