# Generated by Django 4.0.4 on 2022-12-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_annonce_adr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlo', models.CharField(blank=True, max_length=20)),
                ('adr', models.ManyToManyField(to='annonce.adress', verbose_name='Adress')),
            ],
        ),
    ]
