# Generated by Django 4.0.4 on 2022-12-14 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0004_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.annonce', verbose_name='Annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ad',
        ),
        migrations.AddField(
            model_name='fav',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.person', verbose_name='Person'),
        ),
    ]
