# Generated by Django 4.1.5 on 2023-02-08 19:18

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(blank=True, default='/images/default.png', null=True, upload_to=base.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/images/default.png', null=True, upload_to=base.models.upload_to),
        ),
    ]
